language: node_js
node_js:
  - node
  - '7'
  - '6'
  - '5'
  - '4'
  - '0.12'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
notifications:
  email: false
